baseURL = 'https://www.kelvinism.com/'
locale = 'en-us'
title = "Kelvin Nicholson"
ignoreLogs = ['warning-partial-superfluous-prefix']

[permalinks]
posts = "/:year/:month/:title"


[params]
description = "Kelvin Nicholson's personal site, with writing on travel, outdoor adventures, recipes, health experiments, maps, and software projects."
disableSpecial1stPost = true
ShowReadingTime = true
ShowBreadCrumbs = false
defaultTheme = "light"
ShowPostNavLinks = false

[markup.goldmark.renderHooks.image]
  useEmbedded = "never"

[markup.goldmark.renderHooks.link]
  useEmbedded = "never"
